### PR TITLE
Remove unused multipart dependency

### PR DESCRIPTION
**Pull request by wojnilowicz**
| :rocket: This description was created by [Ellipsis](https://www.ellipsis.dev) for commit 4089ba4e2f293f3673888a64b3dde48d8dc6fab6  | 
|--------|

### Summary:
This PR removes the unused `multipart` dependency from the `aw-server` project, simplifying the dependency tree.

**Key points**:
- Removed `multipart` dependency from `aw-server/Cargo.toml`

----
Generated with :heart: by [ellipsis.dev](https://www.ellipsis.dev)

### CODE REVIEW

**Comment by wojnilowicz** [comment]
ping

**Comment by wojnilowicz** [comment]
ping

**Comment by ErikBjare** [comment]
I thought this `multipart` thing was used somewhere? @johan-bjareholt 

Are you sure its not an extra for some other crate? Otherwise, I'll happily merge this. Sorry for the delay.

**Comment by wojnilowicz** [comment]
> I thought this `multipart` thing was used somewhere? @johan-bjareholt
> 
> Are you sure it's not an extra for some other crate? Otherwise, I'll happily merge this. Sorry for the delay.

No problem. As you might already know, I try to package it for Fedora, and still have some dependencies in-progress until I finally get to the aw-server-rust.

multipart is a big dependency to package though, and I successfully built and run aw-server-rust without it, so I want to unload it 🙂

Do you have any idea why is clippy complaining? Environmental issue?

**Comment by ErikBjare** [comment]
Ah, I see! Yeah sure, let's remove it.

I'm not sure why clippy is complaining, but looks like we have the same issue on master, so no worries.

**Comment by ErikBjare** [comment]
I've updated the Cargo.lock as well on the master branch now.

**Pull request merged**
