### PR TITLE
Switched from mpsc to crossbeam

### PR DESCRIPTION
**Pull request by ErikBjare**
Well, that was easy. Hopefully, there'll be no regressions.

Thanks to @stjepang who ported mpsc_requests to crossbeam in https://github.com/crossbeam-rs/crossbeam/issues/353#issuecomment-484013974

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
I'd be fine with merging it into upstream mpsc_requests. Another better option could also be to put it inside a forked repository but upstream is better. Copy-pasting it into aw-server-rust is just sloppy, reverting in #41

**Comment by ErikBjare** [comment]
Oh come on. ~~It will never get merged into upstream due to the reason I stated before~~, and I've never published a crate before.

Edit: LOL, didn't realize you were the author of mpsc_requests. I'll fork it.

**Comment by johan-bjareholt** [comment]
You also don't need to publish it if you don't want, you can fetch a crate straight from a git URL if you want. But publishing a crate is also very easy to du.

**Comment by ErikBjare** [comment]
@johan-bjareholt Yeah, already done (pushed a commit that made the change directly to master: https://github.com/ActivityWatch/aw-server-rust/commit/adfa7568660d8f23a5fed1cd64e37f149b08b371). Was amazingly easy to publish a crate, added you as owner.

**Pull request merged**
