### PR TITLE
Add windows and osx to travis

### PR DESCRIPTION
**Pull request by johan-bjareholt**

### CODE REVIEW

**Comment by ErikBjare** [comment]
Woah, Travis works with Windows now?! Nice!

https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by johan-bjareholt** [comment]
@ErikBjare Found it in another project which did it, seems like it should work fine for our simple use-case of running tests, building a binary and deploying it but we'll see.

**Comment by ErikBjare** [comment]
Can this be merged now? 🤩

**Comment by johan-bjareholt** [comment]
Windows builds are pretty slow due to travis downloadin Rust nightly at every run (instead of having it pre-installed as on the other platforms), otherwise everything looks good!
macOS/Linux take 4-5min while windows takes ~15min

**Pull request merged**
