### PR TITLE
.travis.yml: Fix codecov.io finding the wrong cobertura.xml

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Hopefully this should work, waiting for CI

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
> note: cargo clean exited with code exit code: 101

No idea what's going on here in travis...

**Comment by ErikBjare** [comment]
Stale cache? When the push CI build fails and the PR CI build passes that can sometimes be a problem. Try clearing the cache for master in CI and rerun the PR CI.

**Comment by ErikBjare** [comment]
Seems to work fine now, should we merge @johan-bjareholt?

**Comment by ErikBjare** [comment]
Also, coverage seems to work fine in https://github.com/ActivityWatch/aw-server-rust/pull/88?

**Comment by johan-bjareholt** [comment]
Huh. strange considering that it was broken before.

Maybe codecov.io updated its support for more easily finding merged cobertura xml files?

**Comment by johan-bjareholt** [comment]
In that case I'll close this PR, makes things more complex

**Pull request closed without merging**
