### PR TITLE
aw-models: Add schemars support

### PR DESCRIPTION
**Pull request by johan-bjareholt**

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
I'm having a hard time why it can't find serde and it's respective crates on macOS only. Seems very strange...

**Comment by ErikBjare** [comment]
No idea why that happens, but when searching for it I found: https://www.reddit.com/r/rust/comments/a8ykj8/til_you_dont_need_serde_derive_when_using_the/

Apparently you should just be able to do `use serde::{Serialize, Deserialize}`.

**Comment by johan-bjareholt** [comment]
@ErikBjare Yeah, I also saw that yesterday which is why I removed the "#[macro_use]" and replaced it with use.

I now see in that thread though that it should also be possible to remove serde_derive as a dependency from Cargo.toml and instead add the "derive" feature to serde, will try that.

**Comment by johan-bjareholt** [comment]
Wow, it actually worked!

Will now add a second change which does this for all crates, then I'll merge.

**Pull request merged**
